# Generated by Django 4.2.7 on 2025-07-20 12:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prospects', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_bid', models.IntegerField(validators=[django.core.validators.MinValueValidator(5)])),
                ('current_bid', models.IntegerField(validators=[django.core.validators.MinValueValidator(5)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_bid_time', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('current_bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winning_bids', to='teams.team')),
                ('nominator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominated_bids', to='teams.team')),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='prospects.prospect')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BidHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('bid_time', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bidding.bid')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ['-bid_time'],
                'indexes': [models.Index(fields=['bid'], name='bidding_bid_bid_id_2f8ca3_idx'), models.Index(fields=['team'], name='bidding_bid_team_id_dbee3d_idx'), models.Index(fields=['bid_time'], name='bidding_bid_bid_tim_14f037_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['status'], name='bidding_bid_status_4aca0e_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['prospect'], name='bidding_bid_prospec_6eb833_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['current_bidder'], name='bidding_bid_current_915009_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['last_bid_time'], name='bidding_bid_last_bi_f95a23_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['expires_at'], name='bidding_bid_expires_ff0bcc_idx'),
        ),
    ]
