# Generated by Django 4.2.7 on 2025-07-20 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('SS', 'Shortstop'), ('OF', 'Outfield'), ('UTIL', 'Utility')], max_length=10)),
                ('organization', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('level', models.CharField(choices=[('ROK', 'Rookie'), ('A', 'A'), ('A+', 'A+'), ('AA', 'AA'), ('AAA', 'AAA'), ('MLB', 'MLB')], default='A', max_length=3)),
                ('eta', models.IntegerField(help_text='Expected year of MLB arrival')),
                ('acquired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_prospects', to='teams.team')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='teams.team')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['team'], name='prospects_p_team_id_1a47fe_idx'), models.Index(fields=['organization'], name='prospects_p_organiz_905cbb_idx'), models.Index(fields=['position'], name='prospects_p_positio_b62d8b_idx'), models.Index(fields=['level'], name='prospects_p_level_e41f02_idx'), models.Index(fields=['eta'], name='prospects_p_eta_4f90ae_idx')],
            },
        ),
    ]
